# Generated by Django 5.0.6 on 2024-11-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_employee_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(default='394', max_length=10),
        ),
    ]
