# Generated by Django 5.0.6 on 2024-11-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_employee_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='employeeTo',
            field=models.CharField(default='394', max_length=10),
        ),
    ]
