# Generated by Django 5.1.2 on 2024-11-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_employeeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$OYsnOujQZC3WqaLC1pyGhO$8ecwTGsL6p8cl4lxCtNPgpkqx4JBAUgwMyEWanyI/Yc=', max_length=128),
        ),
    ]
