# Generated by Django 5.1.2 on 2024-11-04 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$8l2B9jFjbeDKOfvuUcUxTs$VWMY26n3/PKeWhwdVgf2Gf4YLRz9xB5A7i38DUUQjRo=', max_length=128),
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason', to='feedback.employee')),
            ],
        ),
    ]
